### ISSUE TITLE
Switch out HTTPotion for Tesla?

### ISSUE THREAD

**Issue by danielberkompas** [danielberkompas/ex_twilio#10]
https://github.com/monterail/tesla

**Comment by KamilLelonek** [comment]
> **WARNING**: Tesla is currently under heavy development, so please don't use it in your production application just yet.

**Comment by danielberkompas** [comment]
@KamilLelonek Yeah, that's what is holding me back from using it right now. For now, I'm sticking with HTTPotion.

**Comment by nathany** [comment]
We use [httpoison](https://github.com/edgurgel/httpoison) for everything else in our app (which uses hackney underneath). Why use potion or tesla?

**Comment by danielberkompas** [comment]
Not going to do this. If anything, I'd rather switch to HTTPoison, since many Elixir apps seem to already depend on Hackney.
