### ISSUE TITLE
Config question with 1.9 coming - this is not an issue, just a question.

### ISSUE THREAD

**Issue by pdgonzalez872** [danielberkompas/ex_twilio#118]
@danielberkompas thanks for the lib. I wanted to ask you:

Config is a hot topic in the Elixir 1.9 release coming up soon. I was wondering how ex_twilio will handle that change or if it won't at all.

There is this blog that deals with passing in the config at every call. What are your thoughts on this subject?
https://michal.muskala.eu/2017/07/30/configuring-elixir-libraries.html

Thanks again!

Paulo

**Comment by danielberkompas** [comment]
I do think that ex_twilio's config will need to be revamped in the future to make it more compatible with releases. I don't have details on that currently though. Happy to review PRs and suggestions, however!
