### ISSUE TITLE
leaking `{ssl_closed, _}` messages from httpoison/hackney

### ISSUE THREAD

**Issue by tsloughter** [danielberkompas/ex_twilio#132]
HTTP requests through `ex_twilio` can result in unmatched `{ssl_closed, _}` messages leaking. I found this was crashing gen_servers that were making requests with ex_twilio. While the issue may ultimately be in hackney, https://github.com/benoitc/hackney/issues/464, I believe a fix in ex_twilio can be based on this patch to another project that experienced the issue, though I guess some difference since ex_twilio is not using hackney directly: https://github.com/opencensus-beam/oc_google_reporter/commit/bb578a5de7b3d986d77e4ad093ae0b82e220c22d

**Comment by danielberkompas** [comment]
I would need more specifics on what specific calls through ExTwilio can result in this error to be able to take action on this.
