### ISSUE TITLE
Where is the documentation for making the webhook receive incoming SMS messages?

### ISSUE THREAD

**Issue by meSmashsta** [danielberkompas/ex_twilio#135]
Hi all! First of all thank you for building this wonderful piece of API.

But I cannot seem to find the documentation similar to this:
https://www.twilio.com/docs/sms/tutorials/how-to-receive-and-reply-java

I'm trying to receive SMS messages in Twilio from users.

**Comment by danielberkompas** [comment]
Unfortunately, I don't have documentation that matches Twilio's for everything. At the moment, you'd need to look at the code and deduce from it how to do different things. Sorry I don't have a better answer!

**Comment by chrisdel101** [comment]
I guess this is project is no longer supported? I have this question too. 

So far I haven't been able to figure out receiving SMS.
