### ISSUE TITLE
Not compatible with Erlang/OTP 24

### ISSUE THREAD

**Issue by marcandre** [danielberkompas/ex_twilio#155]
Erlang/OTP 24 dropped `:crypto.hmac`.

```
=> ex_twilio
Compiling 74 files (.ex)
warning: :crypto.hmac/3 is undefined or private, use crypto:mac/4 instead
  lib/ex_twilio/request_validator.ex:35: ExTwilio.RequestValidator.compute_hmac/2
```

One must use `:crypto.mac/4` which is OTP 22+

FYI, the package `plug_crypto` was updated to tackle the same thing in https://github.com/elixir-plug/plug_crypto/commit/cf901bd2c6694032353072b2c475d18eee7160cf and https://github.com/elixir-plug/plug_crypto/commit/8c1f9271c9a0fb241b1cc970608187246d88d29d

Let me know if I need to write a PR for this.

**Comment by seantanly** [comment]
This is addressed in https://github.com/danielberkompas/ex_twilio/pull/154

**Comment by marcandre** [comment]
Oh, perfect. Closing in favor of #147 / #154
