### ISSUE TITLE
How can I use the Message module?

### ISSUE THREAD

**Issue by AdamBrodzinski** [danielberkompas/ex_twilio#22]
I'm confused on how I should use the sms message module. I've looked at the readme, docs, and source and can't see what needs to be passed into where.

For example I'm trying to send the sms `"Hello World"` to `+15550002222`. Any guidance is much appreciated!

**Comment by benlangfeld** [comment]
Have you tried something like `ExTwilio.Message.create(to: '+15550002222', from: '+14045554321', body: 'Hello World")`?

**Comment by danielberkompas** [comment]
I'm closing this down due to inactivity, and because it looks like @benlangfeld accurately answered the question. @AdamBrodzinski if you have any further questions, let me know!

**Comment by AdamBrodzinski** [comment]
@danielberkompas @benlangfeld   thanks for the help and sorry for the delay. This project got put on the backburner for a bit.

So I tried this and am getting an error with `:ibrowse.send_req/6`. I've looked in the docs but they only say I need a `data` param. Looking into the code it looks like I need two lists, one is optional. 

I've tried:
```
ExTwilio.Message.create(to: '+15550002222', from: '+14045554321', body: 'Hello World")
ExTwilio.Message.create([to: '+15550002222', from: '+14045554321', body: 'Hello World"])
ExTwilio.Message.create([to: '+15550002222', from: '+14045554321', body: 'Hello World"], [])
```

and no success. I just get this error:

```text
Server: localhost:4000 (http)
Request: POST /v2/users/verify
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(:ibrowse_lb, {'api.twilio.com', 443})
        src/ibrowse.erl:323: :ibrowse.send_req/6
        lib/ex_twilio/api.ex:19: ExTwilio.Api.request/3
        lib/ex_twilio/api.ex:65: ExTwilio.Api.create/3
        (badger) web/services/sms.ex:13: Badger.Sms.send/1
        (badger) web/services/sms.ex:27: Badger.Sms.send_verify_code/1
        (badger) web/controllers/user_controller.ex:10: Badger.UserController.verify/2
        (badger) web/controllers/user_controller.ex:1: Badger.UserController.action/2
        (badger) web/controllers/user_controller.ex:1: Badger.UserController.phoenix_controller_pipeline/2
...
```

I'm also nearly positive all the credentials are correct. I copied/pasted them from my prod server to make sure, and double checked.

Any ideas?

**Comment by benlangfeld** [comment]
Drop your mix.lock file here to check the ibrowse dependency?

**Comment by AdamBrodzinski** [comment]
@benlangfeld  wow thanks for the quick reply!

```text
%{"certifi": {:hex, :certifi, "0.3.0"},
  "connection": {:hex, :connection, "1.0.2"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "decimal": {:hex, :decimal, "1.1.1"},
  "ecto": {:hex, :ecto, "1.1.1"},
  "ex_twilio": {:hex, :ex_twilio, "0.1.3"},
  "fs": {:hex, :fs, "0.9.2"},
  "gettext": {:hex, :gettext, "0.9.0"},
  "hackney": {:hex, :hackney, "1.4.8"},
  "httpoison": {:hex, :httpoison, "0.8.0"},
  "httpotion": {:hex, :httpotion, "2.1.0"},
  "ibrowse": {:git, "https://github.com/cmullaparthi/ibrowse.git", "ea3305d21f37eced4fac290f64b068e56df7de80", [tag: "v4.1.2"]},
  "idna": {:hex, :idna, "1.0.3"},
  "inflex": {:hex, :inflex, "1.0.0"},
  "mimerl": {:hex, :mimerl, "1.0.2"},
  "mongodb": {:hex, :mongodb, "0.1.1"},
  "mongodb_ecto": {:hex, :mongodb_ecto, "0.1.2"},
  "phoenix": {:hex, :phoenix, "1.1.1"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.0"},
  "phoenix_html": {:hex, :phoenix_html, "2.3.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.1"},
  "plug": {:hex, :plug, "1.0.3"},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "ranch": {:hex, :ranch, "1.2.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"}}
```

**Comment by benlangfeld** [comment]
So, your ibrowse dependency is an exact match. A quick google leads me to https://github.com/myfreeweb/httpotion/issues/13 which, unless you find a solution before then, will be the point I start looking from tomorrow :)

**Comment by danielberkompas** [comment]
@benlangfeld Thanks for the help on this issue. @AdamBrodzinski I just tried this locally and it worked:

```elixir
ExTwilio.Message.create(to: "+1...", from: "+1...", body: "Message")
```

What version of ExTwilio are you using?

**Comment by AdamBrodzinski** [comment]
@benlangfeld i'm not sure what to look for in the issue... I didn't think that ex_twilio used httppotion?

@danielberkompas  I'm using `0.1.3` and  `"ibrowse": {:git, "https://github.com/cmullaparthi/ibrowse.git", "ea3305d21f37eced4fac290f64b068e56df7de80", [tag: "v4.1.2"]},`

Also tried this in IEX just in case:
```
iex(34)> ExTwilio.Message.create([to: "+15550009999", from: "+15550002222", body: "Hello"])

** (ArgumentError) argument error
    (stdlib) :ets.lookup(:ibrowse_lb, {'api.twilio.com', 443})
             src/ibrowse.erl:323: :ibrowse.send_req/6
             lib/ex_twilio/api.ex:19: ExTwilio.Api.request/3
             lib/ex_twilio/api.ex:65: ExTwilio.Api.create/3
```

**Comment by danielberkompas** [comment]
Is `:ex_twilio` in your `applications` list in your `mix.exs` file? Also, what do you get if you run this in your IEx console?

```elixir
:ets.lookup(:ibrowse_lb, {'api.twilio.com', 443})
```

**Comment by AdamBrodzinski** [comment]
@danielberkompas  I get:

```bash
ex(5)> :ets.lookup(:ibrowse_lb, {'api.twilio.com', 443})
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:ibrowse_lb, {'api.twilio.com', 443})
```

I've also uploded a fresh app repo to replicate this.
https://github.com/AdamBrodzinski/twilio_test/blob/master/web/controllers/page_controller.ex#L6

**Comment by AdamBrodzinski** [comment]
> Is :ex_twilio in your applications list in your mix.exs file? 

Oh... yea that was it :frowning:   I'll PR to add that to the docs.

Thanks!
