### ISSUE TITLE
next_page and etc implementation? 

### ISSUE THREAD

**Issue by waynehoover** [danielberkompas/ex_twilio#23]
Where are the below functions implemented? I only see documentation in the Readme for them, no tests or implementation (I would expect them to be in `ExTwilio.Resource`). Are they not implemented yet or is their implementation just hiding from me?

```
next_page	Given the current page, get the next page.
previous_page	Given the current page, get the previous page.
first_page	Given the current page, get the first page.
last_page	Given the current page, get the last page.
```

**Comment by danielberkompas** [comment]
These functions were actually removed in favor of the stream function. I'm pretty sure you can do everything with stream that you could with them.
