### ISSUE TITLE
Add ability to create Capability tokens

### ISSUE THREAD

**Issue by mikker** [danielberkompas/ex_twilio#28]
I had to create one myself using the fine lib Joken. But this could probably be a nice feature to have built into ex_twilio?

Thank you! 👏🏼

**Comment by danielberkompas** [comment]
Good idea! I'm not sure whether it's best to just recommend Joken if you need those tokens, or add it as a dependency.

**Comment by mikker** [comment]
You're right. Adding a dependency (and it's dependencies) is a very valid concern.

FWIW here's my Joken implementation:

```elixir
defmodule Speaker.TwilioToken do
  import Joken

  @app Application.get_env(:speaker, :twilio_app)
  @sid Application.get_env(:ex_twilio, :account_sid)
  @token Application.get_env(:ex_twilio, :auth_token)

  def generate do
    %{scope: "scope:client:outgoing?appSid=#{@app}"}
    |> token
    |> with_iss(@sid)
    |> with_signer(hs256(@token))
    |> with_exp
    |> sign
    |> get_compact
  end
end
```

Quite easy once I knew what I was going for (Twilo's docs just say "it's JWT -- use one of our libs"). The only "hard" part is shaping the scope string.

**Comment by matteosister** [comment]
@mikker thanks for taking your time to write here a solution. Really appreciated!!!! :heart:
