### ISSUE TITLE
ExTwilio.Message.create throws {:error, "The requested resource /2010-04-01/Messages.json was not found", 404}

### ISSUE THREAD

**Issue by almasakchabayev** [danielberkompas/ex_twilio#33]
Hi I am trying to send a message:

```
ExTwilio.Message.create([to: "<my_number>", from: "<twiio_number>", body: "Hello World!"])
```

However I receive the following response:
```
{:error, "The requested resource /2010-04-01/Messages.json was not found", 404}
```

**Comment by danielberkompas** [comment]
Have you set the configuration variables as shown in the Readme?

https://github.com/danielberkompas/ex_twilio#configuration

**Comment by almasakchabayev** [comment]
Oh I forgot to `source .env` sorry for disturbance

**Comment by danielberkompas** [comment]
It's okay, I probably should add an error message that warns you about that.
