### ISSUE TITLE
Getting error after creating/sending message

### ISSUE THREAD

**Issue by techgaun** [danielberkompas/ex_twilio#37]
When I use `ExTwilio.Message.create`, I receive error but I do receive the message successfully.

The error message reads:

```
(Protocol.UndefinedError) protocol Enumerable not implemented for %ExTwilio.Message{account_sid: nil, api_version: nil, body: nil, date_created: nil, date_sent: nil, date_updated: nil, direction: nil, error_code: nil, error_message: nil, from: nil, num_media: nil, num_segments: nil, price: nil, price_unit: nil, sid: nil, status: nil, subresource_uri: nil, to: nil, uri: nil}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1477: Enum.reduce/3
    (ex_twilio) lib/ex_twilio/parser.ex:104: ExTwilio.Parser.handle_errors/2
```

My code looks something like below:

```
data = [
      from: "+1...",
      to: "+1...",
      body: "Test msg"
    ]
ExTwilio.Message.create(data)
```

Also, I saw mentions of httpoison. Any plan on switching to httpoison.

**Comment by techgaun** [comment]
Was just looking into it again. Apparently, this: https://github.com/danielberkompas/ex_twilio/blob/master/lib/ex_twilio/parser.ex#L51 is causing the issue.

**Comment by danielberkompas** [comment]
@techgaun which version of ExTwilio has this error?

**Comment by techgaun** [comment]
@danielberkompas I encountered this with 0.1.7. I was using the poison v. 1.5.2. With 2.x of poison, 0.1.7 just worked fine.
