### ISSUE TITLE
Accessing the Usage logs

### ISSUE THREAD

**Issue by rlb3** [danielberkompas/ex_twilio#39]
Hello,
Thank you for this library.

I was able to send a SMS message but I would like to see the log of the all the SMS message sent for a sid. How would I do that with this library?

**Comment by danielberkompas** [comment]
@rlb3 Do you mean that you want to see all messages sent to a particular phone number?

**Comment by rlb3** [comment]
Yes, I think there is an API for usage. I'll see if I can find the docs.

**Comment by danielberkompas** [comment]
@rlb3 any luck finding the docs?

**Comment by rlb3** [comment]
Sorry, schedule was very hectic.
But I found it: https://www.twilio.com/docs/api/rest/usage-records

**Comment by rlb3** [comment]
Can close this. Think I found what I want with `all` and `stream`, but I'm having the same problem from issue #38.
