### ISSUE TITLE
where is "Api.get!" defined?

### ISSUE THREAD

**Issue by GildedHonour** [danielberkompas/ex_twilio#48]
https://github.com/danielberkompas/ex_twilio/blob/735725a27e92d96e072ef916d6cdaced6e9905b1/lib/ex_twilio/api.ex#L50

**Comment by danielberkompas** [comment]
It comes from `HTTPoison.Base`, which is `use`d here: https://github.com/danielberkompas/ex_twilio/blob/735725a27e92d96e072ef916d6cdaced6e9905b1/lib/ex_twilio/api.ex#L19
