### ISSUE TITLE
Configure accound_sid and auth_token in run time

### ISSUE THREAD

**Issue by gliush** [danielberkompas/ex_twilio#65]
Hi.

I've tried to use ex_twilio as you specify in documentation and found out the following problem:

1. Do not define `account_sid` & `auth_token` during the build step
2. Build application
3. Define account_sid and auth_token
4. Run application.
5. Get an error (because account_sid and auth_token is undefined)

It seems that all the configurations are compiled into the binaries and any changes to the configuration in runtime doesn't influence it.

I'm strongly against this approach, as we should have different binaries for the dev and for production, we should have access to the production secrets on our building machine, etc.

If you need more details how I'm doing this - don't hesitate to ask.

PS:
If I'm doing smth wrong and there's a workaround - could you explain it please.

**Comment by danielberkompas** [comment]
This is a common issue with many hex packages. The solution is to enable this syntax for configuration:

```
config :ex_twilio, account_sid: {:system, "ACCOUNT_SID"}
```

When you do it the way ExTwilio currently does, the `System.get_env/2` calls happen at compile time rather than runtime.

It shouldn't take me too long once I can get around to it.

**Comment by gliush** [comment]
Do you need help in this?
I can't use current version and currently I'm writing a small library for the functions that I need.

**Comment by danielberkompas** [comment]
@gliush I've added the ability to configure at runtime. A new release will coming shortly, in the meantime you can depend on the git repo.
