### ISSUE TITLE
Setting MaxPrice on message

### ISSUE THREAD

**Issue by pdincau** [danielberkompas/ex_twilio#70]
Is it possible to set MaxPrice when sending an SMS with ex_twilio?

I tried with test credentials this:

    Message.create([to: number, from: from_number, body: body, max_price: "0.1"])

But I am not sure `max_price` is the correct flag because test credentials return canned response.

Thanks!

**Comment by danielberkompas** [comment]
MaxPrice should be `max_price`, yes.
