### ISSUE TITLE
Call vs. Messaging

### ISSUE THREAD

**Issue by ajbraus** [danielberkompas/ex_twilio#84]
Why are all your docs and tutorials around calls? Don't people use this library for messaging much more? I'm stuck. I created one message, but can't create more. I could only find small parts of examples in your issues, but not in the docs. Once I get this working, I'm happy to provide a working example.

**Comment by danielberkompas** [comment]
Can you share your code which isn’t working? I should be able to help out from there. 

I’d be happy to accept a PR updating the documentation once we get it sorted out.

**Comment by scottswezey** [comment]
Potentially unrelated, but if you are dealing with incoming calls, you should check out @danielberkompas's [Telephonist](https://github.com/danielberkompas/telephonist) repo as well.

**Comment by pdgonzalez872** [comment]
@danielberkompas I added a small example to show how Messages can be sent here: https://github.com/danielberkompas/ex_twilio/pull/104
