### ISSUE TITLE
Retrieving A Programmable Chat User.

### ISSUE THREAD

**Issue by inicklas** [danielberkompas/ex_twilio#85]
I've been trying to retrieve a user I created for the programmable chat but I get
```elixir
>> Built url: https://chat.twilio.com/v2/Users/sid-here

{:error,
 "The requested resource /Users/USd908c37b2f444856a5e52122f6370d01 was not found",
 404}
```
when I run `ExTwilio.Api.find(ExTwilio.ProgrammableChat.User, "sid")`

Am I doing anything silly?

**Comment by efexen** [comment]
Twilio scopes users by Services so you need to provide the service SID to scope by, this should work:

```
ExTwilio.Api.find(ExTwilio.ProgrammableChat.User, "sid", service: "service_sid")
```

👍

**Comment by danielberkompas** [comment]
Thanks for jumping in on this one @efexen.
