### ISSUE TITLE
HTTPoison.Error :nxdomain in lib/ex_twilio/api.ex:19

### ISSUE THREAD

**Issue by scottswezey** [danielberkompas/ex_twilio#88]
After upgrading to `0.5.1`, Message API calls through ExTwilio are crashing with an error:

```
HTTPoison.Error :nxdomain in lib/ex_twilio/api.ex:19
```

I've been tried specifying the API domain in my config files, or leaving it out so the defaults apply. I verified that HTTPoison can connect to the `api.twilio.com` domain via `iex -S mix`. All ex_twilio source code I reviewed appears to be correct. Name resolution is working correctly on my testing system inside and out of BEAM.

I can't think of anything else to identify if the issue is local to my system, but wanted to open an issue in case others are finding the same behavior. Feel free to close if you can't reproduce.

Thanks

**Comment by scottswezey** [comment]
While far from conclusive, reverting to ex_twilio version `0.5.0` resolved the issue.

**Comment by DavidVII** [comment]
I'm getting a similar error when calling `Message.all`

```
> ExTwilio.Message.all                                                                                                                    
** (HTTPoison.Error) :nxdomain
    (ex_twilio) lib/ex_twilio/api.ex:19: ExTwilio.Api.request!/5
    (ex_twilio) lib/ex_twilio/result_stream.ex:45: ExTwilio.ResultStream.fetch_page/3
    (elixir) lib/stream.ex:1361: Stream.do_resource/5
    (elixir) lib/enum.ex:1919: Enum.reverse/1
    (elixir) lib/enum.ex:2588: Enum.to_list/1
    (elixir) lib/enum.ex:1163: Enum.into/2```

**Comment by techgaun** [comment]
@scottswezey @DavidVII I made a PR that I believe fixes this issue. The url generation was basically creating invalid urls
