### ISSUE TITLE
Finding Subaccount by Friendly Name

### ISSUE THREAD

**Issue by Lazarus404** [danielberkompas/ex_twilio#93]
In the Twilio docs, one can fetch a subaccount sid by calling Read on the friendly name.  Can this be done in ExTwilio?  I can pull a subaccount by sid, but I would prefer not to have to store the sid in my database and instead call via the friendly name, which I can associate with an existing value.

**Comment by danielberkompas** [comment]
You might be able to pass the friendly name as the `account:` option instead of a SID. Have you tried that?

**Comment by Lazarus404** [comment]
I haven't, but I will give it a try and update here

**Comment by Lazarus404** [comment]
Sadly, it doesn't work.  Message has no :account in its struct definition.  Would it be passed to Twilio?

**Comment by mjaric** [comment]
This works using `all/1` function in Account resource

`ExTwilio.Account.all friendly_name: "some name"`
