### ISSUE TITLE
Utilizing subaccounts / credentials

### ISSUE THREAD

**Issue by sb8244** [danielberkompas/ex_twilio#95]
I was looking over this library out of curiosity (not yet using on a project). I use Twilio Ruby heavily and was comparing against this. One thing that I noticed is that it might not be possible to specify the account sid / token that an API request will be made against. 

Is it possible to specify the sid / token that an API request will make?

If it's not, is this something you'd consider accepting a PR for? I was looking at how I might go about it and do not see an obvious path forward currently which is why I ask.

**Comment by astjohn** [comment]
Try this:
`ExTwilio.Message.create(%{to: "15196356330", from: "16666666666", body: "hellow world"}, [account: "XXX", token: "YYY"])`

**Comment by sb8244** [comment]
Thanks, I think you're right!
